### PR TITLE
Tooltip resource packs + layout tweak

### PR DESCRIPTION
**Pull request by sprunk**
Tooltip implementation (the default `/tooltip 1` one that neither BAR nor ZK use) uses resource packs.

Additionally, tweak tooltip layout:
* each resource now on its own line
* move the default location a bit upwards, partially to make room for the above and partially because games tend to put GUI in the very corner

Layout mockup with 8 resources (with 2 it leaves some room at the bottom)
image

Current for comparison
image

### CODE REVIEW

**Comment by sprunk** [comment]
I had a crash on this build, converting to draft for now.

**Comment by sprunk** [comment]
Unmarked because apparently mainline has some crashes too and I can't find the fault here.

**Comment by saurtron** [comment]
rebased

**Comment by saurtron** [comment]
Tested and seems to work fine (tbh just looked at the tooltip).

Will keep it enabled and see if I see anything strange in the following days before approving myself tho, that comment about crashes is a bit scary XD.

**Pull request merged**
