### PR TITLE
Big building rework

### PR DESCRIPTION
**Pull request by Karolson**
This is a big rework and splitting it into different commits would've been rather annoying, sorry if it's hard to review

Major changes:
- Update to ubuntu:22.10
- Bundle libc.so and some of its dependencies with the build. While this solves the problem of ancient distros, now, if system glibc is newer, Spring will fail to load GPU drivers. So `spring` is replaced with a shell script which first checks whether to preload the system glibc, and then launches `spring-legacy`
- Remove MXE, use mingw from Ubuntu instead
- Remove spring-static-libs and mingwlibs64, use Conan and Ubuntu repos instead (Except DevIL for windoze)
- Don't link Linux statically, bundle libraries with the build (Linking SDL statically wasn't nearly the hard part, but dynamic linking everything still seems a better way. I still left the updated PREFER_STATIC_LIBS option in CMake)
- Use Ninja for building
- Use mold for linking
- Clean up some CMake warnings
- Rework caching on GitHub
- Run legacy, headless and dedicated builds in parallel on GitHub

Obviously needs a ton of testing so a draft for now
Tested on Arch Linux, Wine, Ubuntu 18.04 VM, Windows 10 VM
GitHub builds don't quite work right now, I'll work on that

### CODE REVIEW

**Comment by lhog** [comment]
Ok, review time.

> Update to ubuntu:22.10
> Bundle libc.so and some of its dependencies with the build. While this solves the problem of ancient distros, now, if system glibc is newer, Spring will fail to load GPU drivers. So spring is replaced with a shell script which first checks whether to preload the system glibc, and then launches spring-legacy

Slash that for now.

> Remove MXE, use mingw from Ubuntu instead

@verybadsoldier  please comment why MXE was used in the first place instead of mingw package. I don't quite remember.
Will probably need to slash this too because mingw will be too old on 18.04 unless there are uplifting PPAs

> Remove spring-static-libs and mingwlibs64, use Conan and Ubuntu repos instead (Except DevIL for windoze)

Is DevIL not supplied by Conan on Windows?
I'm very much afraid we lose the compile options granularity with this one. Let's take DevIL: it has conditional compile time support for tons of image format. Some of them we need, some we don't. How do we know which options were compiled in into the Conan supplied binaries?
What kind of runtime library Conan uses on Windows? I vividly recall some of libs not working until I static compiled runtimes inside dlls. They shouldn't rely on dynamic linking to c/c++, that is a must.

> Don't link Linux statically, bundle libraries with the build (Linking SDL statically wasn't nearly the hard part, but dynamic linking everything still seems a better way. I still left the updated PREFER_STATIC_LIBS option in CMake)

Yeah maybe. Does Linux guarantee to look for dynamic libs in the current directory? I was under impression it's not.

> Use Ninja for building

Good change, although originally we used Ninja for building and had to fall back to make since Ninja was failing sometimes (details are lost in time)

> Use mold for linking

Does it also work fine with mingw build?

> Clean up some CMake warnings
> Rework caching on GitHub
> Run legacy, headless and dedicated builds in parallel on GitHub

Very good ones. Thanks!

@verybadsoldier you have bandwidth please have a look as well.

**Comment by Karolson** [comment]
>Is DevIL not supplied by Conan on Windows?

It's not supplied by Conan at all. So on Linux it's fetched from Ubuntu repos and on Windows I've put binaries in a folder.

>I'm very much afraid we lose the compile options granularity with this one. Let's take DevIL: it has conditional compile time support for tons of image format. Some of them we need, some we don't.

That seems like a minor tradeoff for not having to compile everything manually.

>How do we know which options were compiled in into the Conan supplied binaries?

You can look at conan.io or from command line. There are lots of binaries but they seem to have the same build options and only differ in compiler versions/settings, but I'm not sure.

>What kind of runtime library Conan uses on Windows? I vividly recall some of libs not working until I static compiled runtimes inside dlls. They shouldn't rely on dynamic linking to c/c++, that is a must.

There are binaries built with /MT, so this should be ok.

>Does Linux guarantee to look for dynamic libs in the current directory?

Directory can be set at compile time. I set it to (engine dir)/lib for now.

>Does it also work fine with mingw build?

mold doesn't support Windows yet, so no.

**Comment by verybadsoldier** [comment]
> > Remove MXE, use mingw from Ubuntu instead
> 
> @verybadsoldier please comment why MXE was used in the first place instead of mingw package. I don't quite remember. 
IIRC the reason for MXE was the ability to freely choose gcc version instead of being tied to one provided by Ubuntu.

**Comment by lhog** [comment]
> That seems like a minor tradeoff for not having to compile everything manually.

That is a speculation. I don't know what formats are supported in conan build, you don't seem to know either.
Please make sure to test if the following formats are covered: `IL_PNG, IL_JPG, IL_TGA, IL_DDS, IL_BMP, IL_TIF, IL_HDR, IL_EXR`

> There are binaries built with /MT, so this should be ok.

So it's built with MSVC runtime? In theory it should be fine with -MT. Yet.
Let's branch out conan change so it can be built autonomously so the testers could run it extensively on both Linux and Windows

**Comment by Karolson** [comment]
>That is a speculation. I don't know what formats are supported in conan build, you don't seem to know either.

DevIL has all formats enabled by default. I don't know how to test it, but I don't see anything in Ubuntu builds that would disable any, and I don't think Windows builds may have anything disabled either.

>So it's built with MSVC runtime?

There are no mingw prebuilts actually.

>Let's branch out conan change so it can be built autonomously so the testers could run it extensively on both Linux and Windows

I'll do this sometime later. There are still some small fixes needed.

**Comment by lhog** [comment]
Sounds like a plan. If conan builds don't show any flaws, we will move to using them.

**Comment by badosu** [comment]
> (commenting here since only reachable channel I know of outside discord, you can find me at [liberachat IRC server](https://web.libera.chat/#beyond-all-reason) (no registration necessary) or [matrix](https://matrix.to/#/#beyond-all-reason-engine:matrix.org)

@Karolson Do you have any plan on getting this merged? Sorry for bugging you out, it's the sanest way I have of compiling reproducible engine but if there's not timeframe I'll just drop back to whatever is being done at `BAR105` (even if it mean no sane debug build).

**Comment by Karolson** [comment]
Sorry, no time frame, probably a few months until I look at it again. Afaik debug builds work on `BAR105`?

**Comment by sprunk** [comment]
Looks like a lot of things changed underneath, there's multiple merge conflicts. Should this stay open?

**Comment by p2004a** [comment]
I think it's good for it to stay open for whoever might want to pick up build rework. Maybe I would only make it a draft PR.

**Pull request closed without merging**
