### PR TITLE
Remove bitops.h and replace with C++20 <bit>

### PR DESCRIPTION
**Pull request by sprunk**
For code review, not yet tested (but should be no logic change).

### CODE REVIEW

**Comment by sprunk** [comment]
Many `std::bit_something <T>` functions only participate if `T` is an unsigned type, thus the explicit specification in many places. I assume that many of those vars are straightforwardly changeable to be unsigned but maybe some use -1 as a magic value or something like that, idk. Doing that is not in the scope of this patch.

**Comment by lhog** [comment]
Looks good, one ask though is to replace `std::bit_ceil <unsigned> ` with `std::bit_ceil<uint32_t>`. I somehow prefer the integer types with explicitly defined bit width.

**Comment by sprunk** [comment]
I somewhat consciously chose `unsigned` because the type of most of those vars is `signed` (i.e. just `int`), but sure.

**Comment by marcushutchings** [comment]
When did we shift the codebase from C++17 to C++20?

**Comment by sprunk** [comment]
25857a817f7eb8275b966b0e31acce3b7fbf0c71

**Comment by marcushutchings** [comment]
Thnaks. Interesting. The comment on that commit says that it was a test. Why has a test been left in the code?

**Comment by lhog** [comment]
We switched long ago around the time of that commit (but later).

**Comment by sprunk** [comment]
Ah right, the actual switch was 5d2e1e0f13e1c8e4282cc2d421e0030c96028040 (revert revert the above)

**Comment by sprunk** [comment]
Changed `unsigned` casts to `uint32_t`.

**Comment by marcushutchings** [comment]
Why are we changing bitops for the <bit>?

**Comment by lhog** [comment]
Why not? Does it make any sense to keep the custom implementations, if the standard library has their direct counterparts?

**Comment by marcushutchings** [comment]
So you're saying it is being changed because there's now a standard library offering, rather than there was anything wrong with the current implementation? Okay. I was wondering whether there was anything more to it than that.

**Comment by sprunk** [comment]
Actually the current implementation was incorrect at edge cases, for example `next_power_of_2(2) == 2` but `next_power_of_2(1) == 4`. Most of those seemed harmless in current usage though.

**Comment by lhog** [comment]
Please rebase

**Comment by sprunk** [comment]
Rebased

**Pull request merged**
