### PR TITLE
restore window

### PR DESCRIPTION
**Pull request by bianyuanop**
Added restore window functionality in LuaIntro

### CODE REVIEW

**Comment by lhog** [comment]
FYI I've been informed these window manipulation procedures don't work well inside `LuaIntro`.
I can expect two causes:
* The difference in window behavior between Windows and Linux (on the latter it doesn't seem to work correctly)
* The practical lack of message processing in LuaIntro (not possible to fix currently).

**Comment by bianyuanop** [comment]
just checked sdl2 doc, seems need to call SDL_RaiseWindow before calling restore/setmiin/setmax

**Comment by lhog** [comment]
if `SDL_RaiseWindow()` is required as per your message, then why don't you include the call into `SetWindowMinimized/SetWindowMaximized` explicitly?

**Comment by bianyuanop** [comment]
actually SDL_RaiseWindow() only works in my test enviroment(a single cpp file that compiled to a executable). I did some modification on the engine with the RaiseWindow functionality, and found it didn't  work as I expected,  it works fine if i call SetMinimize then call RaiseWindow immediately, but when i put Minimize in LuaIntro in the begining, then put RaiseWinodw in the function LuaIntro:Shutdown. It only minimized itself and never raise again. 

It seems to me the LuaIntro didn't shutdown before i raise the window manually, and when I raise the window, it did RaiseWindow twice. seems like the command got queued but can't get executed in hidden state.

**Comment by lhog** [comment]
First for a clean experiment call your implementations from LuaUI (in-game widgets).
Luaintro is too special to base your observations on.

**Comment by lhog** [comment]
Any progress here?
LuaIntro should get full support of (almost) asynchronous message processing and drawing with reimplementation of `LoadingMT = 1`

**Comment by bianyuanop** [comment]
Actually we found another way to implement the functionality we need, but i think we will retry that using the newest version.

**Comment by lhog** [comment]
Closing for now

**Pull request closed without merging**
