### PR TITLE
fix compilation of springtime tests and upgrade catch2

### PR DESCRIPTION
**Pull request by dzosz**
Enables thread yielding instead of sleep for micro durations that OS probably won't schedule on time. Not sure if this change is welcome as it changes default behavior.
State before:
* buggy DEAD that enables thread yielding with influence of previous sleep times (likely just a faulty logic that was never used). yielding logic was was dead because initial avg_latency values were set to 0.

State after:
* yield thread instead of sleeping for very short durations that take no longer than 5 yield iterations (configurable). initial boundary set to 100us that gets smoothed to actual duration of yield
* At this point of time there's no code in spring that attempts to sleep for such a short duration so it is potential improvement after all

### CODE REVIEW

**Comment by lhog** [comment]
Summoning @marcushutchings for review

**Comment by marcushutchings** [comment]
Maybe I'm missing or overlooking something, but the current logic seems to check out. The initial avg latency being set to 0 seems fine - it can change over time. It seems to me that the original intent of the code was to measure the average inaccuracy of the OS sleep function when it overshoots. Then by measuring that, because it differs between hardware, OSes, and circumstances, if a request comes in that is smaller than the average overshot, then it will use a more accurate, but potentially more performance intensive, thread yield() function.

As the OP has mentioned, we don't have any sleep requests small enough to trigger this; though, I'm not sure why the current code is considered dead.

**Comment by marcushutchings** [comment]
Apologies for sounding dumb: I'm curious about the the change to [rts/lib/catch.hpp](https://github.com/beyond-all-reason/spring/pull/436/files#diff-04018ebeee3af3d2c209d9dca048a5bfa5f728f49a63bd366e1a648e9fc377e0). What was the driving factor that needed this update? GitHub is failing to show the diffs for it.

**Comment by dzosz** [comment]
Thank you Marcus. Your comment made me aware that I misread what was being stored in avgThreadSleepTimeMicroSecs.
My change is not required.
One thing I can do is benchmark original code in critical conditions (1-5 fps) to see whether avgThreadSleepTimeMicroSecs does not grow too much and does not cause unexpected yield calls.

**Comment by dzosz** [comment]
I will fix compilation of tests in separate PR

**Comment by marcushutchings** [comment]
I forgot to mention that I think the use of `std::memory_order_relaxed` is a good one.

**Comment by badosu** [comment]
@dzosz Is there anything you still want to work on this PR?

**Comment by dzosz** [comment]
issue with compiling catch is described here https://github.com/catchorg/Catch2/issues/2421
I have reverted all my changes except for fixing compilation of benchmark files.

I was testing the hypothesis that yielding the thread when timer is not precise enough can cause even more performance issues (imprecise timers might be the cause of high cpu workload) but I was unable to come to any conclusions on my modern hardware (I was using taskset to run spring on two threads). I've got an older laptop so I'll test it there but for now 
I think we can limit the scope to this one fix and merge the PR.

**Comment by badosu** [comment]
@marcushutchings would you mind taking another look?

**Comment by badosu** [comment]
I am unable to review the PR

**Comment by marcushutchings** [comment]
Sorry for the delay, sure I'll take another look.

**Comment by dzosz** [comment]
> Sorry for the delay, sure I'll take another look.

since I reverted all functional changes i'll spare you the time. I'm commiting only fixes for test files in cmakelists

**Pull request merged**
