### PR TITLE
Fix compatibility for old blank map gen

### PR DESCRIPTION
**Pull request by sprunk**
The old keys can still be reused for a "proper" random mapgen in the future, but no reason to break existing projects until then.

### CODE REVIEW

**Comment by sprunk** [comment]
@gajop

**Comment by gajop** [comment]
Thanks! Regarding compatibility, won't this result in black as opposed to green maps? Also, won't I need to still specify `blank_map_height`?

**Comment by sprunk** [comment]
> won't I need to still specify `blank_map_height`?

It seems to default to 50 elmos above the sea if left unspecified (i.e. same as previous).

> won't this result in black as opposed to green maps?

Probably. The ground didn't even render for me on 105-1849 (ie. a handful of commits before the breakage which was in 105-1853) and this PR brings back the same state so I don't actually know what colour the ground is. Perhaps it actually renders and just happens to have 0 alpha? I could investigate on the weekend.

Anyway, ground color could be a parameter. I like the idea of the default being something on the gray scale, and if a parameter was introduced SB could just set it indiscriminately (would get ignored on old green-only engines anyway), but defaulting to green for legacy reasons also sounds fine.

**Comment by gajop** [comment]
> It seems to default to 50 elmos above the sea if left unspecified (i.e. same as previous).

Ok, that sounds good!

> > won't this result in black as opposed to green maps?
> 
> Probably. The ground didn't even render for me on 105-1849 (ie. a handful of commits before the breakage which was in 105-1853) and this PR brings back the same state so I don't actually know what colour the ground is. Perhaps it actually renders and just happens to have 0 alpha? I could investigate on the weekend.

Things seemed fine on `105.1.1-1775-g441af87-bar`, which is the `Latest` release as per: https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-1775-g441af87
I understand it's a bit too old - I assume there have been releases since, they're just not official?

> Anyway, ground color could be a parameter. I like the idea of the default being something on the gray scale, and if a parameter was introduced SB could just set it indiscriminately (would get ignored on old green-only engines anyway), but defaulting to green for legacy reasons also sounds fine.

Yep, I'd be happy to default-to-green. (Perhaps if mapSeed thing is set?) I'd really just prefer not to spend any time on adding compatibility for this.

**Comment by Krogoth100** [comment]
Perhaps `blank_map_color` default to green?

**Comment by sprunk** [comment]
Defaults to green again. Can specify black (or any other color) via `blank_map_color_{r,g,b}`.

**Comment by gajop** [comment]
I can confirm this works well.

**Pull request merged**
