### PR TITLE
Add `Spring.Get{Team,Projectile}AllyTeamID`

### PR DESCRIPTION
**Pull request by sprunk**
Convenience functions for getting the allyTeamID. Interfaces to get these values already existed, but were bad. Compare:

```lua
-- ugly
local _, _, _, _, _, allyTeamID = Spring.GetTeamInfo(teamID)
foo(allyTeamID)

-- less performant, somewhat magic
foo(select(6, Spring.GetTeamInfo(teamID)))

-- nice new possibility
foo(Spring.GetTeamAllyTeamID(teamID))
```

Similar for projectiles (you could get the teamID from `Spring.GetProjectileTeamID` and then do the above).

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Is the `Projectile` version needed, rather than two calls to `Spring.GetProjectileOwnerID`, `Spring.GetTeamAllyTeamID`?
If not, the extra `Team` could be removed `GetTeamAllyTeamID` -> `GetAllyTeamID`.

**Comment by sprunk** [comment]
> Is the Projectile version needed, rather than two calls to Spring.GetProjectileOwnerID, Spring.GetTeamAllyTeamID?

Avoiding two calls is the point.

> If not, the extra Team could be removed GetTeamAllyTeamID -> GetAllyTeamID.

There has to be "team" in the name because there are multiple things that belong to allyteams (units, projectile, teams) for which you could retrieve the allyteam, but the function only accepts team ID there, not unit ID or projectile ID.

**Comment by badosu** [comment]
LGTM :+1: 

Just one point for consideration, would it be desirable to get a pair of `teamId, allyTeamId` on the projectile call (with corresponding rename) or does it have less applications/is less cumbersome?

**Review by badosu — APPROVED** [review]

**Comment by Beherith** [comment]
LGTM too, sounds convenient!

**Pull request merged**
