### PR TITLE
Maintenance: updated vendored minizip code to the version distributed with zlib v1.3.1

### PR DESCRIPTION
**Pull request by jayaddison**
Ports https://github.com/spring/spring/pull/597 to BYAR.  In this case, the source version of `minizip` was from v1.2.11 of `zlib` and the only interim-applied change was d1423c72a88c4e4429d9c4320d17ad719d3a58f7 (meaning that we can cleanup some unreferenced header files).

### CODE REVIEW

**Comment by Beherith** [comment]
Are there any significant changes in zlib?

**Comment by jayaddison** [comment]
@Beherith there's a decent amount in the [`zlib` changelog](https://github.com/madler/zlib/blob/51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf/ChangeLog) since v1.2.11 - I think https://github.com/madler/zlib/pull/843 in particular (a potential buffer-overflow) is worth updating for. Although I don't know for certain whether it affects BYAR-spring, my thinking is that since I have time to prepare and suggest the update, it's worthwhile for me to do that.

**Comment by Beherith** [comment]
Oh its absolutely fine to update for security updates, I was just curious if there were other considerations needing to be taken into account :)

**Comment by jayaddison** [comment]
Yep, a fair concern.  I'm not aware of any, including after spending a bit of time re-reviewing the changelog/commits.  That said, v1.2.x to v1.3.x version boundary does imply that some caution is worthwhile, interface/ABI-wise.  Debian `testing` seems to have upgraded smoothly to v1.3.0 since Nov 2023.

**Comment by jayaddison** [comment]
> Yep, a fair concern. I'm not aware of any, including after spending a bit of time re-reviewing the changelog/commits. That said, v1.2.x to v1.3.x version boundary does imply that some caution is worthwhile, interface/ABI-wise. Debian `testing` seems to have upgraded smoothly to v1.3.0 since Nov 2023.

Correction: `zlib` v1.3.0 was uploaded to Debian _`unstable`_ in Nov 2023; it landed in `testing` (otherwise known as `trixie`) towards the end of December last year.

**Comment by jayaddison** [comment]
A further clarification: this pull request updates only `minizip` code used by `spring`.  Neither `minizip` nor `zlib` have dependencies on each other -- the connection is that `minizip`'s code is distributed as part of source code releases of `zlib` (in a `contrib` subdirectory).

I have to admit to not noticing that `spring` _also_ contains references to `zlib` itself.  It could be worth updating that too.  I'm primarily trying to trace and update vendored copies of `minizip` at the moment.  Debian itself encourages dynamic linking, so that when the system's copy of `minizip` is updated, then applications/libraries that link dynamically benefit from updates transparently, but even so I think it's worth updating the original sources copies too - if nothing else, to reassure people and reduce noise from security scanning tools.

**Comment by Beherith** [comment]
Very worthy pursuit. Have you verified compilation and run success of the engine with the new minizip?

**Comment by jayaddison** [comment]
> Very worthy pursuit. Have you verified compilation and run success of the engine with the new minizip?

Generally I do attempt that with each codebase affected; in the case of `spring` (both vanilla and BYAR), no I have not yet.

**Comment by lhog** [comment]
`smmalloc` is not used by default, I'd suggest to follow the docker way of building it as it's 100% reliable and repeatable. If you're on Windows, the mingw build is also 100% robust with https://winlibs.com/

That aside, I'd like to vendor in https://github.com/zlib-ng/minizip-ng and stop relying on system supplied minizip. IIRC we have certain variability in terms of using this lib from different sources (system or supplied from accompanying engine lib repos).

**Comment by lhog** [comment]
Apparently I've been doing that already for Linux version of the engine: https://github.com/beyond-all-reason/spring-static-libs/blob/master/_scripts/make_static_libs.sh#L239-L267

**Comment by p2004a** [comment]
It's fully known that current engine dependency management is worse than holding on prayers and duct tape, different versions copied over, being pulled in at different situations. Cleanup should not block updating existing vendored dependencies, but replacing dependencies without cleaning up the mess is only making situation worse for any future cleanup.

**Comment by lhog** [comment]
So was this verified to compile and run?

**Comment by jayaddison** [comment]
Thank you @lhog for the containerized build suggestion - I can confirm that this does compile successfully using that approach (although I haven't playtested the results).

Snippets from the build output below:

```
Spring engine version: 105.1.1-2342-gda52e1c BAR105 ()
[  4%] Built target generateVersionFiles
[  5%] Built target C-AIInterface
[ 11%] Built target Cpp-AIWrapper
[ 12%] Built target LegacyCpp-AIWrapper
[ 12%] Built target LegacyCpp-Creg-AIWrapper
[ 23%] Built target BARb
[ 32%] Built target CircuitAI
[ 32%] Built target NullAI
[ 34%] Built target 7zip
[ 34%] Built target minizip
[ 35%] Built target archives
[ 36%] Built target engineSystemNet
[ 36%] Built target smmalloc
[ 38%] Built target streflop
[ 41%] Built target lua
[ 41%] Built target headlessStubs
[ 41%] Built target pr-jsoncpp
[ 43%] Built target unitsync
[ 43%] Built target pr-minizip
[ 43%] Built target pr-base64
[ 43%] Built target pr-md5
[ 43%] Built target pr-sha1
[ 45%] Built target pr-downloader
[ 45%] Built target pr-downloader_cli
[ 45%] Built target cursors.sdz
[ 45%] Built target bitmaps.sdz
[ 45%] Built target springcontent.sdz
[ 45%] Built target maphelper.sdz
[ 45%] Built target basecontent
[ 52%] Built target engineSim
[ 52%] Built target luasocket
[ 52%] Built target rgetc1
[ 54%] Built target sound
[ 74%] Built target engine-legacy
[ 78%] Built target engine-dedicated
[ 80%] Built target no-sound
[100%] Built target engine-headless
...
Creating archive: ../spring_bar_{BAR105}105.1.1-2342-gda52e1c_windows-64-minimal-portable.7z

Items to compress: 289

                                                      
Files read from disk: 240
Archive size: 17358350 bytes (17 MiB)
Everything is Ok
```

**Comment by jayaddison** [comment]
Thanks @lhog!

**Comment by jayaddison** [comment]
Could someone also take a look at https://github.com/beyond-all-reason/pr-downloader/pull/57 ? (the same upgrade, applied to the `pr-downloader` component; it compiles successfully too)

```
[100%] Linking CXX executable pr-downloader
[100%] Built target pr-downloader_cli
```

**Comment by p2004a** [comment]
I will

**Comment by jayaddison** [comment]
Thanks @p2004a!

**Pull request merged**
