### PR TITLE
[Draft] Workaround AI data loss on save/load

### PR DESCRIPTION
**Pull request by rlcevg**
Let it hang for a day, for discussion purposes. The proper fix could be saving AI states and loading alive AIs from saved state and not from initial startscript, but with current approach i found no major issues so far (like leaks or crashes).

### CODE REVIEW

**Comment by rlcevg** [comment]
But i considered only standard scenario where AI dies only with destruction of all units. There may be issues if AI dies somehow without destruction of all units, if that is possible. Got to double-check how events are being dispatched to AI.

**Comment by lhog** [comment]
Thanks, let us know when it's ready.

**Comment by rlcevg** [comment]
Sure, trying to fix through save-load of current AI state at the moment.

**Comment by rlcevg** [comment]
Will re-create PR, based on current HEAD, also fix has nothing in common with workaround in this PR

**Pull request closed without merging**
