### PR TITLE
Fix to 1024 (Sanitize unitDef.corpse)

### PR DESCRIPTION
**Pull request by A-Lias**
Fix to Issue 1024. Sets unitDef.corpse to "" if corpse refers to an invalid feature def.

### CODE REVIEW

**Comment by lhog** [comment]
@sprunk please have a look

**Review by sprunk — CHANGES_REQUESTED** [review]
This is just Lua postprocessing which gets overridden for most games, I think the fix should be in engine. Also the fix looks not even correct (breaks non-builtin corpses).

**Review by sprunk — APPROVED** [review]
It wasn't entirely correct, the sanitisation should happen after the "load map features" step. But I've taken care of that. Thanks!

**Comment by lhog** [comment]
Implemented in https://github.com/beyond-all-reason/spring/pull/1293

**Pull request closed without merging**
