### PR TITLE
Add further once-per-frame zones, colorize top-level zones consistently. 

### PR DESCRIPTION
**Pull request by Beherith**

### CODE REVIEW

**Comment by Beherith** [comment]
Ah, apparently, I should not push to branch that has already been merged. What should my course of action be here? Make a new branch, cherry pick the new commits, delete old branch, and make PR from new branch?

**Comment by sprunk** [comment]
yes

**Comment by lhog** [comment]
You can also rebase to BAR105, and push it under a different remote branch name.

**Comment by sprunk** [comment]
Looks obsoleted by #1198.

**Comment by Beherith** [comment]
> Looks obsoleted by #1198.

Yes thank you, I dont know if I can safely delete the TracyZones branch, given that I have cherry-picked last three commits from the TracyZones branch to the TracyZones2 branch ?

**Comment by sprunk** [comment]
Yes, commits are actually immutable - cherry-picking makes a new, technically completely unrelated commit that just happens to look the same. And branches are just pointers to nodes on the commit tree so deleting a branch can never affect commits reachable from another branch.

**Pull request closed without merging**
