### PR TITLE
Implement https://github.com/beyond-all-reason/spring/issues/391

### PR DESCRIPTION
**Pull request by lhog**
Hopefully it doesn't leak more data than it should

### CODE REVIEW

**Comment by moreginger** [comment]
This would be quite useful for my replay widget attempts. Can I help with testing, or otherwise?

**Comment by sprunk** [comment]
The current implementation leaks some data AFAICT, there's a rewrite suggestion somewhere in the comments.

**Comment by sprunk** [comment]
The unitID and the teamID should also not be available if the attacker is not visible. How about
```cpp
// always pushes 3 values (for `argCount` purposes in the caller)
void LuaUtils::PushAttackerInfo(lua_State* L, const CUnit* const attacker)
{
	if (attacker == nullptr || !IsUnitVisible(L, attacker)) {
		lua_pushnil(L);
		lua_pushnil(L);
		lua_pushnil(L);
	} else {
		lua_pushnumber(L, attacker->id);
		LuaUtils::PushAttackerDef(L, attacker);
		lua_pushnumber(L, attacker->team);
	}
}
```

**Comment by sprunk** [comment]
I think `PushAttackerDef` still had a purpose over just `EffectiveUnitDef` because of the `IsUnitTyped` check. Right now a "plain" unidentified dot will leak its defID.

**Comment by sprunk** [comment]
Now it doesn't leak, but an untyped radar dot still reveals its team and unitID. :P

**Review by sprunk — APPROVED** [review]
Looks good from a gamedev PoV.

**Comment by lhog** [comment]
Windows users can test this exe with https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-1620-gadce3e9 as a base:
[spring-BAR105-fix391.zip](https://github.com/beyond-all-reason/spring/files/10935441/spring-BAR105-fix391.zip)

**Comment by moreginger** [comment]
Excite! Thanks for this :)

**Pull request merged**
