### PR TITLE
[SelectionKeyHandler] Add new Filter `Guarding'.

### PR DESCRIPTION
**Pull request by ecraven**
Filters for front of command queue == CMD_GUARD.

### CODE REVIEW

**Comment by marcushutchings** [comment]
I would like to understand the context of this change. Like: what problem are we trying to solve with this? It makes it easier to review the change.

**Comment by ecraven** [comment]
> I would like to understand the context of this change. Like: what problem are we trying to solve with this? It makes it easier to review the change.

There's already a `Building` and `Waiting`, and for selecting constructors that are guarding a factory, a new command for `Guarding` would be nice. For example, if I need a nearby cons, I can do `AllMap+_Builder_Not_Building_Guarding+_ClearSelection_SelectClosestToCursor+` to get one from somewhere nearby... (ideally we could say "guarding or idle", but that's not possible atm, I think).

**Comment by marcushutchings** [comment]
@badosu does the above explaination make sense and okay with you?

The idea that engineers currently have to 'guard' a factory seems like hack to me; though, that matter is out of scope of this pull request. Ecraven is just working with the situation as it currently stands. I suspect this is fine to merge, but I'm thrown off by the logic that the games seem to have to follow in this case that I'm not really sure. Definately appreciate a game dev to advise on this front.

**Comment by lhog** [comment]
Looks good to me.

**Comment by marcushutchings** [comment]
Okay. Thanks, Ivand.

**Pull request merged**
