### PR TITLE
Bar105 desync auto dump

### PR DESCRIPTION
**Pull request by marcushutchings**
Added spring settings boolean flag `DumpGameStateOnDesync`. When set to true on the server, the server will request all clients to produce a local copy of the current game state (effectively calling `/dumpstate`.)

Fixed issue where desyncs could not be detected before the 300th sim frame (10 seconds)

### CODE REVIEW

**Comment by Beherith** [comment]
Spring.SendCommands("pause 1")

**Comment by marcushutchings** [comment]
I realise sending a pause isn't going to work because it has to originate from a player. If the server is a dedicated one, then it won't have a player ID to hang the request off. Attempting to send a pause without coming from the player is also blocked at the engine level. So, perhaps we'll see if they are any issues without triggering a pause specifically.

**Comment by lhog** [comment]
Looks good 👍

**Comment by lhog** [comment]
We need to rework `for (const auto& m : modelLoader.GetModelsVec()) {` in `void DumpState(int newMinFrameNum, int newMaxFrameNum, int newFramePeriod, bool outputFloats)` though, it no longer is guaranteed to have same order and ids.
I can do that later.

**Comment by marcushutchings** [comment]
That explains what I was seeing. I was wondering if that was related to my local direct connect environment.

**Pull request merged**
