### PR TITLE
Default it to Native for inital engine build.

### PR DESCRIPTION
**Pull request by 12345swordy**

### CODE REVIEW

**Comment by sprunk** [comment]
All are built because otherwise the ones that aren't built will bitrot over time.

**Comment by 12345swordy** [comment]
> All are built because otherwise the ones that aren't built will bitrot over time.

You want me to wrap this in a if statement for msvc then? I can do that.

**Comment by sprunk** [comment]
Not necessarily. I just want anybody dealing with the PR to keep that tradeoff in mind.

**Comment by sprunk** [comment]
#839 seems to contain this change as well and has a better comment, though on the other hand that one does a lot more and seems bitrotting already. Perhaps worth taking a look if there's something salvageable to bring over here?

**Comment by 12345swordy** [comment]
> #839 seems to contain this change as well and has a better comment, though on the other hand that one does a lot more and seems bitrotting already. Perhaps worth taking a look if there's something salvageable to bring over here?

I did look at it though. It better to create small Pull Request for easy to review and for easy to revert in case something went wrong.

**Review by sprunk — APPROVED** [review]

**Pull request merged**
