### PR TITLE
Add named constants for color codes

### PR DESCRIPTION
**Pull request by sprunk**
So people won't need to put magic `\254` etc in their code.

### CODE REVIEW

**Comment by lhog** [comment]
I assume they will be quite cumbersome to use.

Compare `"\255\128\128\128 bla bla \008"` with `Game.textColorCodes.Color .. "\128\128\128 bla bla " .. Game.textColorCodes.Reset`

P.S. I'm not sure `ColorOutline` describes its utility best. This one is really `ColorAndOutline`, perhaps this is what you meant anyway.

**Comment by sprunk** [comment]
I was thinking more about parsers that _read_ messages, like this one:
https://github.com/ZeroK-RTS/Zero-K/blob/548b1b7b07bd57dcde122f6d48191986f5bbf77b/LuaUI/Widgets/chili/Controls/editbox.lua#L123

For _writing_ messages I agree it's unwieldy but I think the option to have it is still good.

**Comment by sprunk** [comment]
Perhaps for writing it would be good to have some sort of `Spring.ColoredText(string, textColor[, outlineColor])` that appends the relevant magic chars at the front and the reset at the end, though that would be something for another PR. I'll do `ColorOutline` -> `ColorAndOutline`.

**Comment by lhog** [comment]
The power of inlined colors is in the ability to change the text color a few times per string, otherwise direct calls to set Primary/Secondary colors exist, so calls like `Spring.ColoredText(string, textColor[, outlineColor])` can't have the same power as the native inlining.

**Comment by sprunk** [comment]
Sure, maybe I'll make a gameside Lua func first and see how it goes. Anyway, that's outside the scope of this PR.

**Pull request merged**
