### PR TITLE
Allow turning off the display of the host IP and username you are connecting with from the connecting screen on load.

### PR DESCRIPTION
**Pull request by Beherith**
By specifying
ShowServerIP = 0; 
in startscript

### CODE REVIEW

**Comment by Beherith** [comment]
Solves #1281

**Review by sprunk — APPROVED** [review]

**Comment by lhog** [comment]
I think the better way is to push a user friendly server name to `"GAME\\ShowServerName` and if empty - show IP.

**Comment by Beherith** [comment]
Thats actually a way better suggestion.

**Review by sprunk — APPROVED** [review]
I don't mind the missing username.

**Pull request merged**
