### PR TITLE
Fix Constructors to use unit radius in build range check for new units

### PR DESCRIPTION
**Pull request by marcushutchings**
Constructors consider unit radius into build range even before the unit is created. They do this once the unit exists, but they haven't been doing this before the unit exists. This change fixes that. Before, there have been issues with constructors getting too close and then having to back off so that they can start building a unit.

The unit radius is declared in the unit's model data.

### CODE REVIEW

**Comment by marcushutchings** [comment]
> MoveInBuildRange(build.pos = CGameHelper::Pos2BuildPos(build, true), 0.0f, true)

Good spot. Okay. I add it there too.

**Comment by KyleAnthonyShepherd** [comment]
image
Everything seems to check out on my side. 
Test case here is on BAR Supreme Strait 1.4, northeast cove. Normally the commander can *just barely* get in range to start building the shipyard. Now the commander easily starts construction from a bit further away, at the range the commander can continue building/repairing the structure

**Comment by marcushutchings** [comment]
@sprunk are there any strong objections from the Zero-K side about this bug fix?

**Comment by sprunk** [comment]
Shouldn't be a problem in general, perhaps there's some edge cases though. Does it handle a case like this well?
image

IIRC currently builders with buildrange short enough not to reach the center across length (but not width) of a long building can struggle a bit if they approach from the bad direction (though they eventually find their way to the side). If that case doesn't get worse then it should be fine. I should be able to test independently in 5 or 24+5 hours.

**Comment by KyleAnthonyShepherd** [comment]
BAR uses cylinder buildranges, so that case has been tested

**Comment by marcushutchings** [comment]
> Shouldn't be a problem in general, so no strong objections. Perhaps there's a weak objection about some edge cases though. Does it handle a case like this well? image
> 
> IIRC currently builders with buildrange short enough not to reach the center across length (but comfrotably reaching via width) of a long building can struggle a bit if they approach from the bad direction (though they eventually find their way to the side). If that case doesn't get worse then it should be fine. I should be able to test independently in 5 or 24+5 hours.

I would expect that situation to improve. Effectively the unit's build radius is as big as it would be if the build target had been spawned. So if a unit has no problem repairing a building, then it should be the same situation as constructing the building now.

**Comment by marcushutchings** [comment]
> Also, the comment says "keep moving until 3D distance to buildPos is LEQ our buildDistance" but build distances can be 2D (infinite vertical cylinder) or 3D. I don't remember off the top of my head which of the two is generally used by BAR or ZK (so it might require some modding or taking a different game to check) but it would be good if both were tested (especially a surface sea constructor building an underwater building at depth == buildrange, but also on land, say across a tall cliff).

From what I can see, the engine only does it this way in this area of code.

**Comment by sprunk** [comment]
I tested and found an issue. Sometimes the nanoframe gets placed correctly when the builder is close enough to be able to nanolathe it, but he will still try to move closer (and possibly even get a bit stuck on the newly created building).

**Comment by KyleAnthonyShepherd** [comment]
Installed Zero-K on my side, and weirdly, using the same compiled engine, BAR is using unit radius, starting build at the outer edge, while ZK is still walking until the midposition is in buildradius.

**Comment by KyleAnthonyShepherd** [comment]
Oh, now I see the issue you pointed out. 
If the `staticrearm` is placed so the midpos is outside the buildradius, but the `staticrearm` radius is inside the buildradius, then the nanoframe gets placed instantly, but the con continues walking until the `staticrearm` midpos is inside the buildradus, and then continues construction.

**Comment by KyleAnthonyShepherd** [comment]
image
Alright, so what is happening is the move goal radius after the nanoframe is placed is too small in ZK

**Comment by KyleAnthonyShepherd** [comment]
ZK gadget `cmd_raw_move.lua` is causing the problems.
Turning off this gadget fixes the problems, the proper movegoal radius is being set when this gadget is off

**Comment by marcushutchings** [comment]
In the old engine what would happen? The unit would walk into the blueprint's yardmap, and then be forced to move to random points until it found a point in the blueprint's radius that it could stand without touching the yardmap?

**Comment by marcushutchings** [comment]
Thanks for investigating the issue @KyleAnthonyShepherd .

**Comment by GoogleFrog** [comment]
The increased raw move goal radius has to depend on the new allowed build radius. Also, this is a pretty significant balance change so I would like some numbers so that I can eyeball an adjustment. Both of these things would be satisfied by a function that gives the new real build radius. Is it as simple as the constructors build radius plus the model radius of the unitdef to be constructed?

**Comment by sprunk** [comment]
> Is it as simple as the constructors build radius plus the model radius of the unitdef to be constructed?

As far as I understand (patch authors can correct me here), yes this is the effective radius, which is also already the radius for assisting existing nanoframes as the patch only makes the radius of spawning a nanoframe match the existing assisting radius.

**Comment by sprunk** [comment]
Looks like there is some extra logic for nanoturrets (immobile builders):
https://github.com/beyond-all-reason/spring/blob/62b80b10136d6cc6312b27b65a6772df78b02114/rts/Sim/Units/CommandAI/BuilderCAI.cpp#L255-L266

Ideally the above function would just be exposed to Lua as `Spring.GetEffectiveBuildRadius(builderID, buildingDefID)` so that games don't have to replicate that logic.

**Comment by marcushutchings** [comment]
Unless I'm reading something there: it looks like those lines (262-263) should be removed.

**Comment by sprunk** [comment]
Should they? I think I agree that arbitrarily gives nanotowers the "buildrange needs to reach center of buildee, not just edge of its radius" behaviour exception is bad but I am unsure if it should be removed, I think ideally it would just be a modrule.

**Comment by marcushutchings** [comment]
Creating a modrule for every little change is not only tiresome, it increases maintainence burden - not just for the code, but also for the documentation.

**Comment by sprunk** [comment]
Sure, if nobody is specifically requesting it at the moment then just remove.

**Comment by sprunk** [comment]
I took the liberty of adding the Lua getter we requested.

**Comment by marcushutchings** [comment]
> I have taken the liberty of adding the Lua getter we requested.

Looks good 

> I have taken the liberty of adding the Lua getter we requested.

That's awesome. Thank you!

**Review by sprunk — APPROVED** [review]

**Comment by marcushutchings** [comment]
Thanks, @sprunk, I was about to add the changelog entires.

**Comment by sprunk** [comment]
Ah sorry. I didn't want to approve without it though.

**Comment by marcushutchings** [comment]
> Ah sorry. I didn't want to approve without it though.

No, I was being genuine. You beat me to it. :) I am genuinely grateful for your initiative.

**Pull request merged**
