### PR TITLE
Integrate Khronos libktx

### PR DESCRIPTION
**Pull request by lhog**
Incomplete and slightly bugged.

### CODE REVIEW

**Comment by badosu** [comment]
We **really** need a build rework to integrate vcdist, conan or whatever. Vendoring and/or relying on spring static libs is a PITA.

**Comment by lhog** [comment]
Yes, I had to cut the original `CMakeLists.txt` from the lib like never before.

**Comment by p2004a** [comment]
Can't we pull this into git submodule? Pulling 0.5mil lines directly into repo is pretty meh...

**Comment by lhog** [comment]
Too bit-rotten to salvage.

**Pull request closed without merging**
