### PR TITLE
added `SetUnitIconDraw` as an alias for `UnitIconSetDraw`

### PR DESCRIPTION
**Pull request by harsha-mangena**
- refer #1531 
- added alias for `SetUnitIconDraw` for `UnitIconSetDraw`.

### CODE REVIEW

**Comment by sprunk** [comment]
Looks untested.

**Comment by harsha-mangena** [comment]
I'm trying to test, but the build is breaking locally. I will test it and update you here.

**Comment by sprunk** [comment]
Try building vanilla upstream without your changes first, in case it turns out your patch contains something that doesn't compile.

**Comment by harsha-mangena** [comment]
Sure, I will check the local build with that.

**Comment by saurtron** [comment]
Hey @harsha-mangena, fixed compilation and polished a bit, hope you don't mind. Thx a lot for preparing this :D

**Comment by lhog** [comment]
LGTM

**Comment by sprunk** [comment]
eae2809daba963d6682fdbc1f91cd117ef9cf60a

**Pull request closed without merging**
