### PR TITLE
Commented profiling

### PR DESCRIPTION
**Pull request by lhog**

### CODE REVIEW

**Comment by sprunk** [comment]
This looks quite useless. What's the point of copy-pasting commented out boilerplate to every function? It's trivial to add if needed and requires a recompilation anyway. IMO either uncomment or remove.

**Comment by 6AKU66** [comment]
"What's the point of copy-pasting commented out boilerplate to every function"
To see deeper picture what functions are lagging the game when it's needed just by applying to all files simple command "replace all".

"It's trivial to add if needed"
It's taking more time and you don't know for sure where function might appear: for example some functions from rts/Sim might actually be in rts/Rendering.

"IMO either uncomment"
It's will make profiling very expensive by RAM and game's performance when profiling is active.

**Comment by sprunk** [comment]
> when it's needed just by applying to all files simple command "replace all".

I think that's what macros (or modern equivalents like `if constexpr`) are for. But sure, the manual version also works.

**Comment by marcushutchings** [comment]
I'm with Sprung on this one. I don't understand the need for this. If you enable all of these trace zones at once your results at higher functions will get skewed and give you incorrect performance information - causing you to chase ghosts. The profiler should have a mode to auto-sample during a run and that's the way you should go if you're looking performance across the whole application at any level. A failure or issue in such a tool to allow that isn't in a good reason to do this to the code.

**Comment by sprunk** [comment]
I made a ticket for what I've identified as the underlying problem, in case this PR gets closed. #1393

**Comment by lhog** [comment]
This should have been a draft, it's unfinished.
All these commented zones were going to be converted into a macros conditionally enabled only on special occasions.

**Comment by marcushutchings** [comment]
Ah, sorry. Though, perhaps there's a wider issue here. Like is there an issue with getting results from sample-based profiling for application wide performance?

**Comment by 6AKU66** [comment]
As i aware there's a problem with enabling sample-based profiling if compiled via WSL. I wasn't able to do this.

**Comment by marcushutchings** [comment]
So, if we compile using native MSVC or mingw32 then it will be fine?

**Comment by p2004a** [comment]
The sampling support with Tracy doesn't work with mingw. It has nothing to do with wsl

**Review by sprunk — APPROVED** [review]
Would've been better to fix sampling for mingw, but I understand that would be hard. So this is also fine since it's relatively unintrusive.

**Pull request merged**
