### PR TITLE
Introducing SDL2 keyscancodes to Spring bindings :)

### PR DESCRIPTION
**Pull request by FIr3baL**
Introducing SDL2 keyscancodes to Spring bindings :)
Motivation:
- On german keyboards z and y are switched compared with us layout, also ; [ ] and other keys are no existing on german layout
- french AZERTY has other keys switched
- Lets enable the world to play spring :)

Purpose:
- Bind game actions to a positional key on a generic keyboard (SDL2 references to USB keyboard)
- manufacturers of keyboard change prints on keys instead of changing physical sent scancodes to system
- lets use those scancodes

This Commit calls GameController:KeyPressedSC(keyScanCode, keySym, isRepeat)
Then KeyPressedSC acts as an adapter to KeyPressed.
Derived classes will run Keypressed if KeyPressedSC is not implemented.

Included and tested with this Commit following GameControllers have been made Scancode-Ready:
- CGame

Same adapter works in CInputreceiver, derived classes can implement KeyPressedSC, otherwise KeyPressed is called
- CGuiHandler
- CLuaInputReceiver

EventClient also handles KeyPressedSC
- LuaHandle

Included widgets.lua and actions.lua to enable keyPressed Bindings and actions in lua

### CODE REVIEW

**Comment by Beherith** [comment]
This sounds magnificent, though does it break backward compatibility in any way?

**Comment by FIr3baL** [comment]
Without backward compatibility was ready in Jan.

I worked around all existing keyreceivers and made it to work beside of it.
Of course it needs intense testing.

This is the result of my work since Oct '21 - aprox. more than 100 hours work

**Comment by Beherith** [comment]
Ok, thank you for the explanation, ill push the merge button if noone objects :)

**Comment by Beherith** [comment]
Do modifier keys also trigger repeats?

**Comment by FIr3baL** [comment]
> Do modifier keys also trigger repeats?

I didnt test repeat keysets at all

**Comment by FIr3baL** [comment]
Tell me a repeat key keyset to test pls

**Comment by lhog** [comment]
Id like to have a look at the code first. Don't merge yet plz.

**Comment by FIr3baL** [comment]
First concern, that came to my mind:
Since it´s possible to bind to the same key in 2 different ways at the same time, possibly it has an impact to the chain of consumed keys.
Can´t imagine an example right away, but certailny an issue to look for.

**Comment by FIr3baL** [comment]
@Beherith 
Repeat keys work at least for spring actions
i.e.: ```{ "Any+`,Any+`",    "drawlabel" }```
or with Scancodes : ```bind Any+SC_`,Any+SC_`	drawlabel```
but it worked with keysyms before as well
Repeat keys for lua actions should be fixed by https://github.com/beyond-all-reason/Beyond-All-Reason/pull/864

**Comment by Beherith** [comment]
Thank you so much Fireball, you work is far above my understanding of the engine though, so ill give ivand some more time to review this. If matters get pressing, i can try merging it.

**Comment by lhog** [comment]
I'm afraid I can't review without running it (and won't be for who knows how long).
Too many changes to comprehend on the paper.

As long as the code doesn't break the compatibility I'm good with merge. I doubt this functionality will spread outside of BAR as game any time soon, so even in case something needs to be changed later, it'll be easier to do within a closed ecosystem.

Thanks and sorry it takes long I'm dealing with circumstances outside of my control.

**Comment by icexuick** [comment]
@lhog is there anything i/we can do for you?
I feel bad you're in a bad situation!! ;(

**Pull request merged**
