### PR TITLE
Revert 980dda9bf26d3d2ac2b1212eefe7f748a6231184

### PR DESCRIPTION
**Pull request by sprunk**
There is no `weapontype` field in WeaponDefs, the previous was kosher all along though.
thx [BoS]nixtux!

### CODE REVIEW

**Comment by lhog** [comment]
Unsure it's the case
`WEAPONTAG(std::string, type).externalName("weaponType").defaultValue("Cannon");` does exist
Some code in the engine depends on `type == "Shield"` runtime check, so it must exist one way or another in Lua too (try type, weaponType).

I'm constrained as far as running the actual game at the moment, but I'd suggest to tap out a weapondef of some shield weapon and find out why it's missing, instead of reverting back to the past:

```
    for name,param in weaponDef:pairs() do
      Spring.Echo(name,param)
    end
```

**Comment by sprunk** [comment]
> WEAPONTAG(std::string, type).externalName("weaponType").defaultValue("Cannon"); does exist

Yes. This means that if you have `unit.lua` you can write `weaponType  = "Cannon"` when defining the unit's weapons.
But if you have `gadget.lua` you cannot read `WeaponDefs[x].weaponType` because it does not exist.

> Some code in the engine depends on type == "Shield" runtime check, so it must exist one way or another in Lua too (try type, weaponType). I'd suggest to tap out a weapondef of some shield weapon and find out why it's missing

Yes. [It exists as `type`](https://github.com/Beyond-All-Reason/spring/blob/BAR105/rts/Lua/LuaWeaponDefs.cpp#L465). This means this patch could also have been made to say `wd.type == "Shield"`, that check would be equivalent but I decided on a revert to the original because the patch that changed it was never needed and never worked.

> P.S. IIRC Lua Definition tags and Lua read tags are totally different things. This can explain the phenomena.

Yes, exactly. As far as I can tell nixtux wrote the original patch because `isShield` had been [deprecated](https://github.com/beyond-all-reason/spring/commit/f71494fc56c77164562378551d009bd9226698d7) and [removed](https://github.com/beyond-all-reason/spring/commit/e69eeb21bbcd5fb1acb5b53a17bc5bbd495289b2) from the Definition tags just before and he was clueless about this distinction. But [it's still there in Read tags](https://github.com/Beyond-All-Reason/spring/blob/BAR105/rts/Lua/LuaWeaponDefs.cpp#L556), always has been. The patch was never needed and never worked. As to how it survived for 10 years without somebody noticing: `setupdefs.lua` is an obscure and undocumented helper file so my guess is that nobody competent enough to see the mistake even knew it exists and everybody just parsed weapons manually in gadgets with a proper check.

**Comment by lhog** [comment]
Yeah both approaches should work.
IDK, up to you which path to take.

**Comment by sprunk** [comment]
I think I'd prefer `isShield` over `type == "Shield"` because https://github.com/spring/spring/pull/570 already got merged with `isShield`.

**Comment by lhog** [comment]
> I think I'd prefer `isShield` over `type == "Shield"` because [spring#570](https://github.com/spring/spring/pull/570) already got merged with `isShield`.

That is a bad argument as the mainline spring makes very little sense now, but w/e.

**Pull request merged**
