### PR TITLE
implement animated wayland hw cursor

### LINKED ISSUE #253: Implement Wayland HardwareCursor
Currently Wayland can't enable HardwareCursor.

This is where the class is defined: https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/HwMouseCursor.cpp#L178-L195

References:

- https://wayland-book.com/protocol-design/interfaces-reqs-events.html
- https://bugaevc.gitbooks.io/writing-wayland-clients/content/beyond-the-black-square/cursors.html

### PR DESCRIPTION
**Pull request by dzosz**
fixes #253 
Is resizing to next power of 2 required? It seems to be in the right size for me.

### CODE REVIEW

**Comment by lhog** [comment]
> Is resizing to next power of 2 required? It seems to be in the right size for me.

In modern times usually not, but it's really up to the display protocol to impose such requirements. If Wayland docs don't say something like that explicitly then it shouldn't be required.

**Comment by dzosz** [comment]
With wayland protocol spring is responsible for animating the cursor. Instead manually implementing it we can rely on SDL which has already implemented it here: https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandmouse.c#L482 
Possible improvements
* move to different thread that does not stutter the animation when fps is low
* make it default hw cursor

**Comment by lhog** [comment]
Is this ready for merge? Do you plan to add animation thread?

**Comment by dzosz** [comment]
This RP is ready to merge. I will look investigate options to fix cursor animation under low framerate as a separate issue.

**Pull request merged**
