### PR TITLE
Add reclaim data to TeamStatistics

### PR DESCRIPTION
**Pull request by keelefi**
Track reclaim data and expose it in GetTeamStatsHistory().

### CODE REVIEW

**Comment by sprunk** [comment]
How does this relate to #1305?

**Comment by keelefi** [comment]
> How does this relate to #1305?

Not in any way that I'm aware of. I have neither written nor tested the other PR.

**Comment by sprunk** [comment]
Sure, but both do the same thing with some minute differences.

**Comment by A-Lias** [comment]
Awesome-- two independent PRs about this is great evidence that this feature is in high demand.

I think this PR by @keelefi has a cleaner implementation than my PR (#1305), assuming this one works correctly (I have not tested it).

My implementation adds these statistic changes in EndGameBox and the DemoTool, which this PR does not do. Even though EndGameBox will eventually be removed, I think it's a useful temporary addition.

I will close my PR #1305 in favor of this one. @keelefi, will you consider pulling my changes in EndGameBox and DemoTool to this branch and including them in the PR? There should be no merge conflicts.

**Comment by lhog** [comment]
Good, please collaborate to take best of both.

**Comment by keelefi** [comment]
> I think this PR by @keelefi has a cleaner implementation than my PR (#1305)

Thank you for your input. I'm new to spring/recoil development so I cannot be the judge of this.

> assuming this one works correctly (I have not tested it).

I have to admit I'm not exactly sure of how to go about testing recoil changes. What I did here is that I launched a copy BAR including Spectator HUD widget and modified the widget to use the new data provided by the engine. I could not spot any incorrect behavior, but recoil is more than just BAR. Also, I'm not sure if I know all the different ways one can accomplish reclaim. Then again, I was very careful to check that there was no remaining code paths untouched...

> My implementation adds these statistic changes in EndGameBox and the DemoTool, which this PR does not do. Even though EndGameBox will eventually be removed, I think it's a useful temporary addition.

Thank you, I added the commit to this PR. I tested that it compiles, but didn't yet have time to test in-game.

**Comment by A-Lias** [comment]
> Thank you for your input. I'm new to spring/recoil development so I cannot be the judge of this.

I'm also new :) That makes it especially funny we both contributed basically the same feature within a day of each other.

> I have to admit I'm not exactly sure of how to go about testing recoil changes. What I did here is that I launched a copy BAR including Spectator HUD widget and modified the widget to use the new data provided by the engine. I could not spot any incorrect behavior, but recoil is more than just BAR. Also, I'm not sure if I know all the different ways one can accomplish reclaim. Then again, I was very careful to check that there was no remaining code paths untouched...

I tested commit [ada30b5](https://github.com/beyond-all-reason/spring/pull/1312/commits/ada30b5f960c051a1573bec367d2c20c3d203024) only in BAR, but it works and I'm fairly certain this update is all that's needed. I used the BAR [TeamStats widget](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_teamstats.lua) with some modifications to check during the game, and then the end game graph also is displaying everything correctly.

**Comment by keelefi** [comment]
I just concluded some extra testing around this PR. I tested it in Beyond All Reason and followed how `GetTeamStatsHistory()` changed `metalReclaimed` and `energyReclaimed` over time. Here's what I observed:

* Reclaiming buildings work correctly. For instance, reclaiming arm solar will increase metal reclaimed by `155` when building is reclaimed.
* Reclaiming terran features work correctly. For instance, reclaiming trees will channel energy once per second and energy reclaimed is updated accordingly.
* Reclaiming wreckage work correctly.

In addition, I tested two things I'm not sure how they would work.

* Letting building decay will increase metal, but will not show as metal reclaimed.
* Reclaiming damaged building will still give full metal.

**Comment by A-Lias** [comment]
I also tested this PR and found no problems. I included a test of multiple builders reclaiming the same unit or feature and found the reclaim statistics were correctly in this case also.

@lhog, this should be ready for review.

**Review by sprunk — APPROVED** [review]
I slightly dislike the `bool isReclaim` param added to most `AddResources` functions but it's not a dealbreaker.

**Comment by keelefi** [comment]
Thank you @A-Lias for testing and thank you @sprunk for the review.

> I slightly dislike the `bool isReclaim` param added to most `AddResources` functions

Yes, I'm not a fan myself either. As every call to `CUnit::IssueResourceOrder()` has set `isReclaim` to `true`, it can be removed. But this is a high-level design decision on compartmentalization. Do you want the extra parameter removed or would you rather see some other design?

**Comment by sprunk** [comment]
Personally I think it can stay but let's wait to see what other maintainers say.

**Comment by Beherith** [comment]
Does reclaiming a living unit count as reclaim?

**Comment by keelefi** [comment]
> Does reclaiming a living unit count as reclaim?

I tested reclaiming stouts and for each stout metal reclaim was increased by 225 metal.

This is as I was expecting based on the fact that reclaiming buildings like solars will count as reclaim as well.

**Comment by A-Lias** [comment]
It appears that https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2607 (the [spectator_hud](https://github.com/keelefi/Beyond-All-Reason/tree/spectator-hud) widget) wants to make use of the reclaim statistics that this PR would enable. I believe casting of recent BAR tournaments relied on the spectator_hud pretty extensively, so if we are no longer in a feature freeze, I think this would be useful to add.

>I slightly dislike the bool isReclaim param added to most AddResources functions but it's not a dealbreaker.

One alternative way to track reclaim in #1305 did not have this param, but the downside was that every reclaim call to AddBuildPower() needed to get and update the relevant teamStats. I closed that PR in favor of this because it seems much cleaner.

I actually see value in modifying AddResources() to take a generationType = {"extracted", "converted", "reclaimedFeature", "reclaimedUnit", "windGenerated", "tidalGenerated", ... } instead of the bool isReclaim. This would allow hyper-detailed economy statistics that I'm sure some folks would be interested in. It also helps address the double-counting problem that widgets like spectator_hud face in differentiating between metal "produced" by reclaiming a T1/T2 lab versus metal produced through extraction/conversion versus metal produced by reclaiming features/wrecks.

I don't think these types of statistics can be tracked in Lua without an engine modification. If this sounds like a reasonable direction (and if @keelefi agrees that it would be useful), let me know and I'll open a ticket and move this discussion over there.

**Comment by keelefi** [comment]
> It appears that [beyond-all-reason/Beyond-All-Reason#2607](https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2607) (the [spectator_hud](https://github.com/keelefi/Beyond-All-Reason/tree/spectator-hud) widget) wants to make use of the reclaim statistics that this PR would enable. 

Yes. The most requested feature by far for Spectator HUD is to add information about metal reclaim.

> > I slightly dislike the bool isReclaim param added to most AddResources functions but it's not a dealbreaker.
> 
> One alternative way to track reclaim in #1305 did not have this param, but the downside was that every reclaim call to AddBuildPower() needed to get and update the relevant teamStats. I closed that PR in favor of this because it seems much cleaner.

It didn't become exactly clear to me what the problem with `isReclaim` is, but if it's a performance concern, then all functions could be renamed like `IssueResourceReclaimOrder`. These functions are anyway only used for reclaim currently. There's also an optional argument in all functions calls which is never set and therefore could be removed.

> I actually see value in modifying AddResources() to take a generationType = {"extracted", "converted", "reclaimedFeature", "reclaimedUnit", "windGenerated", "tidalGenerated", ... } instead of the bool isReclaim.

We discussed this on Discord with Sprunk a few months ago. Sprunk said this is not possible to do in the engine. I believe that to be true. Based on my quick code exploration I think there's no way to differentiate between metal extractor and metal converter in game engine. As far as the engine is concerned, both metal extractors and metal converters use energy to generate metal.

> I don't think these types of statistics can be tracked in Lua without an engine modification.

Yes.

> If this sounds like a reasonable direction (and if @keelefi agrees that it would be useful), let me know and I'll open a ticket and move this discussion over there.

Yes, this is very much requested by high skilled players. When you play on a decently high skill level, aspects like this become rather important. Both for replay analysis and for the esports side of BAR, I think a lot of players would like to see differentiation of sources of resource income.

P.S. On a personal note I feel I need to say that I have found the code review process both in BAR and Recoil engine too slow for my liking. Therefore, I have moved on to other projects and I'm not currently interested in contributing.

**Comment by sprunk** [comment]
> It didn't become exactly clear to me what the problem with `isReclaim` is

It just looks arbitrary, what's so special about reclaim that it gets its own parameter and other types of generation don't? But I know the answer to that and I'm not specifically asking to do anything about it, it's fine to keep as is.

>> modifying AddResources() to take a generationType
>
> Sprunk said this is not possible to do in the engine

Just to be clear:
* it's not currently (cleanly) possible for a game to differentiate various types of production implemented via native engine  (for example an energy generator implemented via the `energyMake` unit def tag vs a wind generator implemented via the `windGenerator` unit def tag).
* it would totally be possible to make the engine track native types of production by adding a bunch of parameters like was just done for reclaim. I am ambivalent though because each of those types can be differentiated further at a level the engine has no idea about (for example when reclaiming features there's a meaningful difference between wreckage and pre-placed rocks, or when generating energy there's a meaningful difference between T1 structures and T2 structures). So perhaps the way would be to just expose events to Lua and let the game decide how to assign those resources to buckets. And then again, reclaim is already exposed to Lua (via `AllowFeatureBuildStep`) but that is considered too expensive (so this patch actually doesn't bring any new capability, it just improves performance). Ultimately I'm not sure.
* it is already possible for a game to differentiate anything implemented via Lua, or that the engine already tells Lua about via events. In particular, BAR [almost reimplements wind generators](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/unit_windmill_control.lua#L56) via Lua so it could tell how much income comes from windgens if it wanted to. It seems to [already be tracking metal makers](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/game_energy_conversion.lua#L331) (aka converters) in some way.

**Comment by p2004a** [comment]
`TeamStatistics` wasn't changed in 11 years, it is serialized as is, and send via Autohost network interface as a C object https://github.com/beyond-all-reason/spring/blob/25a4c1ef2475468d7ab782e8f9d343e5a3d85c1b/rts/Net/AutohostInterface.cpp#L156.

So, this change is breaking backwards compatibility of what is send on the wire to Autohost, I see that message is used by SPADS, so it's not theoretical, this should be reverted from master and rework to not break backwards compatibility on that interface.

**Comment by p2004a** [comment]
Ok, it apparently doesn't even build. Reverted in #1558.

**Comment by A-Lias** [comment]
> `TeamStatistics` wasn't changed in 11 years, it is serialized as is, and send via Autohost network interface as a C object
> 
> https://github.com/beyond-all-reason/spring/blob/25a4c1ef2475468d7ab782e8f9d343e5a3d85c1b/rts/Net/AutohostInterface.cpp#L156
> 
> .
> So, this change is breaking backwards compatibility of what is send on the wire to Autohost, I see that message is used by SPADS, so it's not theoretical, this should be reverted from master and rework to not break backwards compatibility on that interface.

I wish that these details would have been mentioned sometime in the last 4 months that this PR has sat around as "approved". 🫠 

New contributors can't be expected to recognize things like this on their own. I don't understand how @Beherith and @sprunk and @lhog can all comment on a PR by two new contributors without anyone raising a red flag about incompatibility.

> Ok, it apparently doesn't even build. Reverted in https://github.com/beyond-all-reason/spring/pull/1558.

There have been 137 commits pushed to master since @sprunk approved this PR in February (4 months ago). It's not surprising that it no longer builds.


P.S. I have chosen to no longer contribute to this project. This is primarily due to the project's broken code review/ contribution process and dysfunctional management. It looks like @keelefi has also chosen the same after his brief interaction submitting this PR.

When it comes to me, you aren't losing out on much-- I had little to offer. My background is in data analytics, not game engines, and I wanted to contribute to Recoil as a way of giving back to an open source project that I appreciated (and as a fun challenge). But I am sad that the project is missing out on real talent (like @keelefi and certainly others) because approved PRs are sat on for 4 months... only to then be recognized as incompatible and reverted.

This PR isn't the only example of this project's code review failures. I'm still waiting on #1293 to be merged (approved 4 months ago)... and that one is a fix I wrote for a posted issue... which was specifically tagged as "good first issue" 😅

Reclaim statistics has been one of the most requested features for the widget built by @keelefi. It's a shame that 4 months later there is no solution, and that the two people most motivated to contribute to this have left the project.

**Comment by p2004a** [comment]
First, I'm sorry about your extremely poor experience with contributing 😟.

> without anyone raising a red flag about incompatibility.

I think they likely just simply didn't know. Engine is huge and old. It's a total coincidence that I did implementation of this protocol and also [fixed engine docs](https://github.com/beyond-all-reason/spring/commit/f363fafb2a3e0622a26894fa7436d97632e0d0de) around it a *month* ago and then happened to notice this PR and look inside when it landed on master (which I rarely do as engine is not my primary focus area).

**Comment by keelefi** [comment]
@p2004a would you mind explaining why the corresponding change cannot be implemented in Autohost / SPADS?

**Comment by p2004a** [comment]
It can, but it simply breaking backwards compatibility across the ecosystem on this interface and implications weren't discussed. All this software now would need to be updated to be engine version aware, change behavior depending on engine version that is running, you have to make sure all those changes are deployed across ecosystem (e.g does it break ZK?) before new engine version can be picked up.

It's of course possible to do it all, but this is IMHO not a change that can go in without addressing this concern.

Maybe instead the engine should still emit the old version, and emit new statistics via a new message type which explicitly states how the backwards compatibility should look like (e.g. new fileds added only at the end of the struct). Or maybe it's already the case where adding the fields at the end of the existing struct is safe when looking at affected implementations and this is a simple change in this PR to move fields at the end.

**Comment by Yaribz** [comment]
As far as SPADS is concerned, there should be no problem at all in adding new optional fields *at the end* of the `TeamStatistics` structure included in the `GAME_TEAMSTAT` messages (current SPADS version should just ignore them, and I can easily add full support for them in a new version).

**Comment by p2004a** [comment]
Same for my experimental implementation of autohost. @sprunk can you comment about ZK world? Any other implementations there are/we should think about?

**Comment by Beherith** [comment]
My apologies for looking at just the PR text and giving insufficient feedback based on that. 
I didnt even realize that any change to the `TeamStatistics` object cascades into having to check compatibilty with:
- SPADS
- Middleware server (Teiserver and ZKLobby) 
- SPADS plugins
- BAR Replay site
- Replay parser library

To give broader context, only very few people have the knowledge scope to review a PR and how it affects all consumers of the engine, and all other connected components. 

We were in a feature freeze this spring to investigate deeper bugs, and our lead engine developer is currently relocating, which understandably takes priority over voluteering. 

I apologize for the inconveniences caused :(

**Comment by lhog** [comment]
I think we can resolve the issue by making the external facing data structure a separate entity (and maybe version it moving on).
Hold tight I'll have a look as soon as a have a keyboard (couple of weeks hopefully)

**Comment by sprunk** [comment]
Sorry for the fiasco, 100% my fault for not letting you know that there was a feature freeze and not pinging the people who usually do merging after the review after the freeze was over.

> can you comment about ZK world?

As far as I can tell the ZK autohost completely ignores those stats.

**Pull request merged**
