### PR TITLE
Add tracy zones to previously unmarked areas

### PR DESCRIPTION
**Pull request by Beherith**
To help get a better picture of sim and draw loads. 
Note that these additions dont spam zones, usually only marked only once per sim or draw frame.

### CODE REVIEW

**Comment by lhog** [comment]
Looks safe enough to merge even during the merge freeze. @marcushutchings do you agree?

**Comment by marcushutchings** [comment]
To double check these won't add additional entries on the /debug view will they?

**Comment by Beherith** [comment]
> To double check these won't add additional entries on the /debug view will they?

Nope

**Comment by marcushutchings** [comment]
No game impacting logic changes detected. Approved.

**Pull request merged**
