### PR TITLE
End game graph/log scale

### PR DESCRIPTION
**Pull request by John-194**
Added log scale option.

Before:
Screenshot 2024-03-16 190918

After:
Screenshot 2024-03-16 190928

### CODE REVIEW

**Comment by sprunk** [comment]
Make a widget? I don't think this is the engine's job.

**Comment by John-194** [comment]
> Make a widget? I don't think this is the engine's job.

It isn't the engine's job but it is currently doing it. Making a widget requires me to learn lua, which I currently don't want to do and even then it will take a while to built everything from scratch.

**Comment by sprunk** [comment]
> It isn't the engine's job but it is currently doing it.

Yes, but it's just there to start you out. Eventually you'll need to move to a Lua implementation anyway. If anything, it's a good argument to remove it and put a Lua implementation in basecontent since it doesn't really do anything vital. Perhaps the upcoming rmlui rewrite of native engine GUI would be an excellent opportunity to do that.

**Comment by John-194** [comment]
> > It isn't the engine's job but it is currently doing it.
> 
> Yes, but it's just there to start you out. Eventually you'll need to move to a Lua implementation anyway. If anything, it's a good argument to remove it and put a Lua implementation in basecontent since it doesn't really do anything vital. Perhaps the upcoming rmlui rewrite of native engine GUI would be an excellent opportunity to do that.

So until rmlui gets implemented and the new graphs are made, maybe we can use this implementation? I would really like to view my graphs in log scale without having to wait for the new stuff (I believe other people would like that too). If we must wait for the new stuff (who knows for how long), should I delete my PRs?

**Comment by sprunk** [comment]
> I would really like to view my graphs in log scale without having to wait for the new stuff (I believe other people would like that too), but if we must wait for the new stuff (who knows for how long)

You don't have to wait for the new stuff, the Lua API to do so has been there for about 15 years and there's existing implementations (e.g. https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_chili_endgraph.lua ) that I would recommend stealing.

> should I delete my PRs?

The other PR looks fine since it's just a tweak. To this one, normally I'd say yes but given that there is going to be a rewrite anyway I think we can accept it as well.

**Review by sprunk — APPROVED** [review]
There's a bit of bad whitespace all around but it probably doesn't matter if this is due a rewrite anyway.

**Comment by John-194** [comment]
> There's a bit of bad whitespace all around but it probably doesn't matter if this is due a rewrite anyway.

Form my end (VS Code), the whitespace looks consistent with the surrounding code. Although when looking through GitHub's "Files changed", I can see some missing spaces, I don't know why that is.

**Comment by sprunk** [comment]
spaces vs tabs

**Comment by Beherith** [comment]
Base 10 log is overkill, I would choose either log2 or natural log.

Can the UV coordinates of the background images (graphpaper.bmp) be adjusted, and games can supply their graphpaperlogX.bmp to get logX tiling?

Handling all negative log10's as zero isn't very pretty for the non-resource type stuff. Does std::log handle the -inf correctly for values of zero?

Can any numbers of the graph be negative, where log isundef or NaN and the resulting clamping fails?

**Comment by John-194** [comment]
> Base 10 log is overkill, I would choose either log2 or natural log.

The base doesn't matter because the graph and axis values get scaled accordingly to display correct values (not log).

> Can the UV coordinates of the background images (graphpaper.bmp) be adjusted, and games can supply their graphpaperlogX.bmp to get logX tiling?

You mean something like this? Would probably take some extra time to implement non-linearly placed axis values. 
image

> Handling all negative log10's as zero isn't very pretty for the non-resource type stuff. Does std::log handle the -inf correctly for values of zero?
> Can any numbers of the graph be negative, where log isundef or NaN and the resulting clamping fails?

It seems fine for zero, nan should throw an error although I didn't notice that. Should I place the v0 and v1 clamp (v0 = v0 <= 0.0f ? 0.0f : v0), before the logs and skip log calculation if zero?

**Comment by sprunk** [comment]
rmlUI has been merged so it would be ideal to move the graphs from engine into a rml widget.

**Comment by lhog** [comment]
Guess we can merge it as is, it's not clear if and when it's going to be migrated to RML.

**Comment by sprunk** [comment]
Sure

**Pull request merged**
