### PR TITLE
Add environmental damage types for each kill type

### LINKED ISSUE #1638: Add "environmental" damage types for each kill type
There's a bunch of virtual weapon types that represent various things that can happen to the unit:
https://github.com/beyond-all-reason/spring/blob/19d1a003ed2b327ec0f96767bfd8cc26c5766419/rts/Lua/LuaConstGame.cpp#L261-L264

Task:
* go through invocations of `CUnit::KillUnit` and find out what types of death exist (e.g.: i am a factory buildee and was cancelled; i am a factory buildee and my factory died; i am a transportee and my transport died; i was reclaimed; i self-d'd; i am a crashed aircraft; etc). 
* add a unique named weaponDefID constant for each death type (except the trivial one that happens in `CUnit::DoDamage`, which is how the existing virtual weapons are used) and expose it to Lua via the `envDamageTypes` table.
* one of the types will be "killed via Lua" - keep this one at the bottom (lowest ID) and add an appropriate comment such that it stays that way. This lets games mark custom types by doing something like
```lua
envTypes.CullingStrike      = envTypes.Lua - 1
envTypes.SummonTimerExpired = envTypes.Lua - 2
```

Listing out the damage types is sufficient, actually passing them anywhere is not in the scope of this ticket (but see #1639).

### PR DESCRIPTION
**Pull request by keelefi**
Closes #1638

### CODE REVIEW

**Comment by keelefi** [comment]
Draft PR because I'm not sure if I like the naming of the variables and I want to sleep on it.

I welcome any comments or feedback, now or later.

**Comment by sprunk** [comment]
Looks good! Seems to be missing some reasons for death:

1) out-of-bounds
https://github.com/beyond-all-reason/spring/blob/2ef0794f99d9215f44c07ec7aae57fe8c4600caa/rts/Sim/MoveTypes/Systems/GroundMoveSystem.cpp#L107-L108

2) aircraft crash
https://github.com/beyond-all-reason/spring/blob/2ef0794f99d9215f44c07ec7aae57fe8c4600caa/rts/Sim/MoveTypes/StrafeAirMoveType.cpp#L525-L526

3) turned into feature
https://github.com/beyond-all-reason/spring/blob/2ef0794f99d9215f44c07ec7aae57fe8c4600caa/rts/Sim/Units/Unit.cpp#L450

4) some of the missing ones above may be what you meant by "killed by game", but that is a pretty bad name. Every death is ultimately via game mechanics one way or another.
https://github.com/beyond-all-reason/spring/blob/9c7cefeb2a18645b488b93f56fbfe443dd43d8fb/rts/Lua/LuaConstGame.cpp#L278

5) the "unit script" death is COB, not LUS. LUS uses regular Lua interfaces.
https://github.com/beyond-all-reason/spring/blob/2ef0794f99d9215f44c07ec7aae57fe8c4600caa/rts/Sim/Units/Scripts/UnitScript.cpp#L1258
https://github.com/beyond-all-reason/spring/blob/9c7cefeb2a18645b488b93f56fbfe443dd43d8fb/rts/Lua/LuaConstGame.cpp#L277

6) I'd rename `Decay` to `ConstructionDecay` because any custom timeout mechanic could also be called just "decay".
https://github.com/beyond-all-reason/spring/blob/9c7cefeb2a18645b488b93f56fbfe443dd43d8fb/rts/Lua/LuaConstGame.cpp#L272

**Comment by keelefi** [comment]
(if you'd rather see full code, this is more or less what I'm working with: https://github.com/beyond-all-reason/spring/compare/BAR105...keelefi:spring:kill-unit-add-damage-types)

>     1. out-of-bounds

I'm planning to use `DAMAGE_KILLED_GAME` for this and the likes of it. Although, now that I think of it, it should be `ENGINE` rather than `GAME`.

>     2. aircraft crash

`DAMAGE_COLLISION_GROUND` and `DAMAGE_COLLISION_OBJECT` already exist, I was planning to use those for the `ForcedKillUnit()` calls from the air move types.

>     3. turned into feature

Thanks a lot, this I really don't understand what this is and how it happens.

What should it be named?

>     5. the "unit script" death is COB, not LUS. LUS uses regular Lua interfaces.

Thanks, I did not know this. I'll change it to `DAMAGE_COB`? And the Lua variable to `LuaCOB`?

>     6. I'd rename `Decay` to `ConstructionDecay` because any custom timeout mechanic could also be called just "decay".

Good point, thanks a lot.

Btw I'm still lacking damage types for `KillUnit()` calls from

https://github.com/beyond-all-reason/spring/blob/2ef0794f99d9215f44c07ec7aae57fe8c4600caa/rts/Sim/Units/Unit.cpp#L959

https://github.com/beyond-all-reason/spring/blob/2ef0794f99d9215f44c07ec7aae57fe8c4600caa/rts/Sim/Units/UnitHandler.cpp#L279

**Comment by sprunk** [comment]
> 2. I was planning to use existing `DAMAGE_COLLISION_GROUND` for crashing aircraft

I think using a separate constant is good for two reasons:
* it's trivial for a gamedev to make the existing value represent aircrashes if they have their own ID (`if id == aircrash then id = collision`) but it's much harder to go the other way around and distinguish crashes from collisions if they are under the same ID
* and there are plausible reasons for a gamedev to handle them separately. For example for an aircraft to crash it usually has to be shot down, so maybe a game already considers being shot down a "kill" and will want to ignore the real death according to various mechanics because it already processed the kill. While a kill via collision may be the first and the last time the game receives an event about the collidee.

> 1. I'm planning to use `DAMAGE_KILLED_GAME/ENGINE` for this and the likes of it.

Similar reasoning as above. For example maybe going out of bounds is more of an error case than just being killed in one of the other ways so the game may want to do something about it (idk, produce logs and send an error report?) and it's nice to be able to distinguish that this specifically happened.

> 3. I really don't understand what "turned into feature" is and how it happens. What should it be named?

It happens when the unit is set to turn itself into a feature on completion via the `isFeature` unit def tag, that's for example how Dragon's Teeth used to work until recently in BAR. Being called "TurnedIntoFeature" sounds alright.

> 5. I'll change it to `DAMAGE_COB`? And the Lua variable to `LuaCOB`?

`DAMAGE_COB` sounds fine. There is no Lua involved in killing the unit so I'd go with just `COB` for the Lua var.

> still lacking damage type for `Unit.cpp : 959`

A unit dies this way when health is directly set to less than 0 without any damage involved. Perhaps call it `HealthUnder0` or `SetNegativeHealth` or something like that?

> damage type for `UnitHandler.cpp : 279`

Currently this is reachable only from Lua, so will pass along whatever weaponID Lua code decided the unit was killed by. It doesn't need its own value.

**Comment by keelefi** [comment]
Thank you greatly for all the very thorough explanations :bow: 

I basically implemented all of your suggestions with the only exception that deaths from unit scripts are `DAMAGE_UNIT_SCRIPT` and `UnitScript`.

**Comment by keelefi** [comment]
How these are thought to be used can be seen here: https://github.com/beyond-all-reason/spring/pull/1665/commits/d1df939f266d0eb668eded5c7a0d28da5a061515

**Review by sprunk — APPROVED** [review]

**Comment by sprunk** [comment]
One more minor thing (shouldn't cause conflicts in follow-up patches): https://github.com/keelefi/spring/pull/2

**Comment by lhog** [comment]
Looks to be included in https://github.com/beyond-all-reason/spring/commit/aed398d4c263e2b8350be55b8acb2f626752c9c5#diff-85b82291d073a0f5bf8b0a4d29693156937cb4359544e2816acc61f3980a21e9R283 ?

**Comment by sprunk** [comment]
Yes, #1669 is based on this and wasn't really ready. I'll fix it up later.

**Comment by keelefi** [comment]
@sprunk you will make a separate PR for the fixup commit that closes https://github.com/beyond-all-reason/spring/issues/1638 am I right?

**Comment by sprunk** [comment]
Yes.

**Pull request closed without merging**
