### PR TITLE
Improved unit formation move command.

### PR DESCRIPTION
**Pull request by marcushutchings**
Tested and ready to go. We have a feature freeze at the moment, so this will have to wait until after the upcoming engine release.

### CODE REVIEW

**Comment by badosu** [comment]
Was there a change in behavior or is it a refactoring?

**Comment by marcushutchings** [comment]
Sorry, I had yet to get around to writing the description. This is an improvement. Currently when units are given a formation move command, they move about often getting in each other's way. This is especially noticeable if you give a group the Alt+Move command and then again but directly behind where you'll see all units move across each other as their target positions are fliped on the X and Y axis. This makes units move in a more sensible fashion - meaning that units are able to adopt formations significantly faster than before. The group move command has cases where it randomizes the position of different unit types to avoid creating weak flanks - this improved movement honours that. In essence the end result is effectively the same, but the formations are assumed much more quickly.

**Comment by badosu** [comment]
Nice, thank you for the detailed explanation. Keep in mind for testing on BAR (you probably already know this, but useful for others that might read it) you need to disable custom formations widget.

**Comment by marcushutchings** [comment]
Thanks for the heads up. I found that the default controls use this code fine. Right Mouse drag, Alt+Right Mouse, and M+Left Mouse drag seemed to all use this code.

**Comment by badosu** [comment]
Interesting, maybe I'm wrong but custom formations should be triggered, I would expect one to be overriding the other. Or maybe I misunderstand how the widget works.

**Comment by marcushutchings** [comment]
You know more than me. I didn't even know about a custom formations widget!

**Comment by sprunk** [comment]
A screenshot comparison would be good to have for clarity/changelog resons, possibly with an artificially salient or simplified case (as far as I can tell the relevant difference may already happen with 4 units in a 2x2 formation?).

> I didn't even know about a custom formations widget!

Tangentially to engine or this PR, but this sounds like it could be major gameside breakage.

**Comment by marcushutchings** [comment]
> A screenshot comparison would be good to have for clarity/changelog resons, possibly with an artificially salient or simplified case (as far as I can tell the relevant difference may already happen with 4 units in a 2x2 formation?).
> 
> > I didn't even know about a custom formations widget!
> 
> Tangentially to engine or this PR, but this sounds like it could be major gameside breakage.

Beyond the line formation move command, and hold formation move - is there anything else in Zero-K that i can check?

**Comment by sprunk** [comment]
ZK doesn't expose any ways to use the native engine formation move UI AFAIK so probably not.

**Comment by marcushutchings** [comment]
I've tested the various movement commands I coudl find in Zero-K and there are no ill-effects.

**Comment by marcushutchings** [comment]
For videos showing the difference, see here: https://discord.com/channels/549281623154229250/724924957074915358/1063154978589519942

Sorry, the videos are too big for GitHub.

**Pull request merged**
