### PR TITLE
Fix Keycode names

### PR DESCRIPTION
**Pull request by MasterBel2**

### CODE REVIEW

**Comment by MasterBel2** [comment]
To test this, add the following widgets:
https://github.com/MasterBel2/Master-GUI-Framework
https://github.com/MasterBel2/Master-Keytracker

Master-GUI-Framework must be enabled for Master-Keytracker to work.

**Comment by lhog** [comment]
@badosu can you have a look?

**Comment by badosu** [comment]
It's not clear what this fixes. Care to elaborate?

In fact this reverts a fix where the predictor does not ever find a key code by passing a hard coded 0 instead of the key code. Which would make it always return the hex value label for the key ode instead of it's name

**Comment by MasterBel2** [comment]
> Which would make it always return the hex value label for the key code instead of it's name
Right, seems I'd got it in my head that the hex code was the "name" it was supposed to be returning – "because it was the old behaviour it must be the correct behaviour" or something. Ty for confirming that. I'll close the PR and fix my widget in a more proper way.

**Pull request closed without merging**
