### PR TITLE
ensure timed-out client is disconnected so they can't cause desyncs.

### PR DESCRIPTION
**Pull request by marcushutchings**
Fixes https://github.com/beyond-all-reason/spring/issues/1406

### CODE REVIEW

**Comment by sprunk** [comment]
How does a timed-out client cause desyncs? Aren't they sending no packets either way?

**Comment by 6AKU66** [comment]
Not sure if i correct: Client is starting to think that game ended and it's causing problems a lot of problems including a desync.

**Comment by marcushutchings** [comment]
> How does a timed-out client cause desyncs? Aren't they sending no packets either way?

A timed out client triggers a local game end. They aren't supposed to be connected to the server, but in many cases they are which means they are still receiving and sending packets. Having triggered a local-only game end, the game state will match the game state of the other clients.

**Review by sprunk — APPROVED** [review]
> A timed out client triggers a local game end.

Perhaps that is the real problem? It could trigger some sort of "timed out" event instead and keep the game running. I always wanted to be able to tell apart timeouts and real game-overs in Lua `wupget:GameOver` for the player who dropped.

But this change sounds good too.

**Pull request merged**
