### PR TITLE
Add rewritten documentation for `select'.

### PR DESCRIPTION
**Pull request by ecraven**

### CODE REVIEW

**Comment by lhog** [comment]
The documentation is something we lack the most, so thanks for the contribution.

That said, I'm not certain whether the docs should be kept as in-tree files like you did or somewhere outside, like for example https://springrts.com/wiki/Lua:Main or https://github.com/beyond-all-reason/spring/wiki

Historically we tended to lean towards the latter i.e. outside docs, but if you prefer so, I can merge this PR too as the existence of the doc regardless of location is better than the lack of such.

**Comment by ecraven** [comment]
I'm OK with any approach, just tell me where I should put it.

**Comment by lhog** [comment]
Will be best to put it on BAR/spring wiki as well.
Will merge once the Guard PR reviewed and merged first.

**Comment by marcushutchings** [comment]
Perhaps the documentation should only exist in one place (to ensure single source of truth) - the wiki is a sensible to place it. So I think merging into the code as well would be a mistake.

**Comment by Beherith** [comment]
I see the guard PR is in, so im merging this, Thank you!

**Pull request merged**
