### PR TITLE
Switch to faster deque

### PR DESCRIPTION
**Pull request by marcushutchings**
queue wraps deque and reports on the net suggest it is between 10-20% slower than deque.

### CODE REVIEW

**Comment by sprunk** [comment]
What sort of reports on the net? Queue is just a deque adapter so they're the same.

**Comment by marcushutchings** [comment]
Questions have been raised on C++ forums. The issue is around iteration specifically. https://codeforces.com/blog/entry/72064 We don't need queue here.

**Comment by sprunk** [comment]
>  queue wraps deque and hides functionality of deque, which changes how it works

That's just the exposed interface though, the data layout etc are still the same and should produce the same code if the compilation settings are any good (see below).

> The issue is around iteration specifically.

Does queue even let you iterate other than via a series of `pop`s? Do you plan to follow up with further changes and iterate without popping? If yes then the change is fine but then say so.

> Questions have been raised on C++ forums

That link doesn't specify compiler or flags. I've seen other "questions on C++ forums" and they also tend to be terrible and fail to specify flags and be on old compiler versions. Meanwhile I put this into godbolt, `gcc 13.2`, `-O3`:
```
#include <queue>
#include <deque>
void pop_q(std::queue <int> &x, int y) { x.pop(); x.push(y);  }
void pop_deq(std::deque <int> &x, int y) { x.pop_front(); x.push_back(y);  }
```
and they both produce the exact same assembly. We mostly have pushes and pops, and compile with `-O3`, so I think I'd trust the above as a first approximation more than random students asking on stackoverflow or codeforces.

**Comment by sprunk** [comment]
Just to be clear, I don't mind the actual contents of the patch. I just mind the "20% faster according to randoms on the internet" justification, any other would be fine.

**Comment by marcushutchings** [comment]
This was a change to avoid potential issues in the future, rather than anything specific to now - given I was in this area of code. Though, thinking about it I'm not sure whether someone would ever try iterating over them. We can worry about it if it happens. I'll scrap this PR.

**Pull request closed without merging**
