### PR TITLE
Delete Buildbot

### PR DESCRIPTION
**Pull request by 12345swordy**
Got approval from ivand regarding this. It didn't effect me building the engine so unless anyone objects this, I am deleting the folder.

### CODE REVIEW

**Review by sprunk — APPROVED** [review]
There seem to be two things done here:
* produce core engine artifacts (i.e. just run compilation and build the engine). This part is no longer useful and good to remove.
* do a bunch of release-adjacent tasks. Run some sort of tests (!), upload docs to mediawiki etc. Perhaps people who usually do infra/CI (@p2004a ?) and docs/site (@badosu ?) could look if there is anything useful down there. I expect not really so don't consider it a blocker if they don't respond.

**Comment by sprunk** [comment]
Yes, I mean more like "oh this is solving a nice edge case we haven't thought of". For example it changes C++ `std::string` to Lua `string` for weapondef doc [which our GitHub actions runner doesn't do](1674).

**Comment by p2004a** [comment]
I looked through it, there is a bunch of interesting stuff, so I will remember it existed: nothing is lost in git history.

**Comment by badosu** [comment]
> Yes, I mean more like "oh this is solving a nice edge case we haven't thought of". For example it [changes](https://github.com/beyond-all-reason/spring/blob/fd0ea0b464062d404a549c340adfbeffa705ff60/buildbot/slave/wiki/update_weapondefs_page.sh#L54-L55) C++ `std::string` to Lua `string` for weapondef doc [which our GitHub actions runner doesn't do](1674).

Interesting, I've never ran buildbot locally so I was unaware of this. Even if it is desirable to have that postprocessing (since it's already there), I don't think the value is good for the complexity. The output format is something that should be encoded (and processed) by the engine code itself imo.

**Pull request merged**
