### PR TITLE
Remove `tdfID` weapon def

### PR DESCRIPTION
**Pull request by sprunk**
Replaced with regular ID in COB, removed elsewhere.

### CODE REVIEW

**Comment by marcushutchings** [comment]
So how would games track weaponDef ids? If they get hit by weapon id 20, how do they know what weapon that is?

**Comment by sprunk** [comment]
They still get the weapon def id. This patch removes tdf id.

**Comment by sprunk** [comment]
No known game sets the tag:
[tdfid path:*.lua](https://github.com/search?q=tdfid+path%3A*.lua)
[tdfid path:*.tdf](https://github.com/search?q=tdfid+path%3A*.tdf)

**Comment by marcushutchings** [comment]
Does anything else need to be removed from the engine if tdf files are not going to be supported?

**Comment by sprunk** [comment]
This doesn't affect tdf file support, only the `tdfID` weapon def, which only has tdf in the name and is otherwise unrelated to tdf files.

**Pull request merged**
