### PR TITLE
use CPUID to detect core count for Intel CPUs. FIx CPU pinning for Alder Lake Intel CPUs.

### PR DESCRIPTION
**Pull request by marcushutchings**
I get a significant multi-thread performance improvement on my Intel 6-core laptop with this change.

### CODE REVIEW

**Comment by marcushutchings** [comment]
Further testing required. I can't easily tell in my most recent testing.

**Comment by Beherith** [comment]
Is there a build of this? Cause it needs 3 way testing on new AMD, old intel, and new intel with P and E cores.

**Comment by marcushutchings** [comment]
@Beherith, I rebased to latest BAR105 and produced this build for you: https://github.com/beyond-all-reason/spring/actions/runs/3046069559

**Comment by marcushutchings** [comment]
Testing from RTX who has access to an Intel Alderlake found that the Linux OS is prioritising our support threads on the efficient cores rather than the performance cores. This suggests to me that we need to pin the threads to the performance cores. As a result of this however means we will not spawn threads on the efficient cores, because work on the efficient cores needs the flexibility to be moved to the performance cores if the performance cores are finished, and that won't happen with the current pattern of behaviour of our threads.

**Comment by marcushutchings** [comment]
So the changes here correctly detect cores on Alder Lake (12th gen Intel core.) The CPU pinning remains as is. The changes have been tested on my laptop for general purpose CPU cores and RTX has tested these changes on an Alder lake based machine.

**Comment by marcushutchings** [comment]
Second successful test by Gajop, confirming the expected behaviour and performance improvement.

**Pull request merged**
