### PR TITLE
purge spring-legacy manpage

### PR DESCRIPTION
**Pull request by rfht**
Seems left over, while spring-legacy binary isn't built anymore. Therefore remove the now meaningless manpage.

### CODE REVIEW

**Comment by lhog** [comment]
I don't mind you take out all `manpages` part, it's not maintained nor will be.

**Comment by rfht** [comment]
I looked through it and getting rid of all manpages would mean getting rid of `doc/manpages/` and `doc/CMakeLists.txt` and unhooking the `doc/` subdirectory from the main `CMakeLists.txt`. Looks to me like the rest of doc can stay...

**Comment by lhog** [comment]
Please make sure this doesn't break the installation process, i.e. `make install` and alike.

**Comment by rfht** [comment]
I made a whole build and install with this patch on OpenBSD without issues. As it's all wrapped into `if (UNIX)` and there are no other places referencing the man pages, there isn't any reason to suspect that other Unix systems would have unanticipated issues. I'll add removal of the mention of manpages in a comment in `CMakeLists.txt`...

**Review by sprunk — APPROVED** [review]

**Pull request merged**
