### PR TITLE
Dolly camera

### PR DESCRIPTION
**Pull request by loveridge**
Branched from my previous camera MRs.

Provides a new camera controller that disregards user input and instead allows for camera automation. Supports position to be controlled by a specific point, or a NURBS curve. Position control can also be relative to world, or relative to the look target. The look target can be a specific point, a unit to track, or another NURBS curve.

### CODE REVIEW

**Comment by lhog** [comment]
Is this one complete?

**Comment by sprunk** [comment]
It might depend on some of the older PRs IIRC

**Comment by loveridge** [comment]
> Is this one complete?

This is complete, but branched off of other MRs which should be merged first to enable an easier review of this one. https://github.com/beyond-all-reason/spring/pull/1589 and https://github.com/beyond-all-reason/spring/pull/1644 are included in this

**Comment by lhog** [comment]
@loveridge please (squash)merge this one as well as well as https://github.com/beyond-all-reason/spring/pull/1589 & https://github.com/beyond-all-reason/spring/pull/1644 as you see fit.

**Pull request merged**
